#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duanmau1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyPhongTro")]
	public partial class QuanLyPhongTroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void UpdateCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void DeleteCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void InsertCHU_TRO(CHU_TRO instance);
    partial void UpdateCHU_TRO(CHU_TRO instance);
    partial void DeleteCHU_TRO(CHU_TRO instance);
    partial void InsertDICH_VU(DICH_VU instance);
    partial void UpdateDICH_VU(DICH_VU instance);
    partial void DeleteDICH_VU(DICH_VU instance);
    partial void InsertHOA_DON(HOA_DON instance);
    partial void UpdateHOA_DON(HOA_DON instance);
    partial void DeleteHOA_DON(HOA_DON instance);
    partial void InsertHOP_DONG_THUE(HOP_DONG_THUE instance);
    partial void UpdateHOP_DONG_THUE(HOP_DONG_THUE instance);
    partial void DeleteHOP_DONG_THUE(HOP_DONG_THUE instance);
    partial void InsertNGUOI_THUE(NGUOI_THUE instance);
    partial void UpdateNGUOI_THUE(NGUOI_THUE instance);
    partial void DeleteNGUOI_THUE(NGUOI_THUE instance);
    partial void InsertPHONG_TRO(PHONG_TRO instance);
    partial void UpdatePHONG_TRO(PHONG_TRO instance);
    partial void DeletePHONG_TRO(PHONG_TRO instance);
    #endregion
		
		public QuanLyPhongTroDataContext() : 
				base(global::duanmau1.Properties.Settings.Default.QuanLyPhongTroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this.GetTable<CHI_TIET_HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<CHU_TRO> CHU_TROs
		{
			get
			{
				return this.GetTable<CHU_TRO>();
			}
		}
		
		public System.Data.Linq.Table<DICH_VU> DICH_VUs
		{
			get
			{
				return this.GetTable<DICH_VU>();
			}
		}
		
		public System.Data.Linq.Table<HOA_DON> HOA_DONs
		{
			get
			{
				return this.GetTable<HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<HOP_DONG_THUE> HOP_DONG_THUEs
		{
			get
			{
				return this.GetTable<HOP_DONG_THUE>();
			}
		}
		
		public System.Data.Linq.Table<NGUOI_THUE> NGUOI_THUEs
		{
			get
			{
				return this.GetTable<NGUOI_THUE>();
			}
		}
		
		public System.Data.Linq.Table<PHONG_TRO> PHONG_TROs
		{
			get
			{
				return this.GetTable<PHONG_TRO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_HOA_DON")]
	public partial class CHI_TIET_HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTHD;
		
		private string _MaHoaDon;
		
		private string _MaDichVu;
		
		private System.DateTime _ThangNam;
		
		private double _ChiSoCu;
		
		private double _ChiSoMoi;
		
		private string _LoaiTieuThu;
		
		private EntityRef<DICH_VU> _DICH_VU;
		
		private EntityRef<HOA_DON> _HOA_DON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTHDChanging(string value);
    partial void OnMaCTHDChanged();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaDichVuChanging(string value);
    partial void OnMaDichVuChanged();
    partial void OnThangNamChanging(System.DateTime value);
    partial void OnThangNamChanged();
    partial void OnChiSoCuChanging(double value);
    partial void OnChiSoCuChanged();
    partial void OnChiSoMoiChanging(double value);
    partial void OnChiSoMoiChanged();
    partial void OnLoaiTieuThuChanging(string value);
    partial void OnLoaiTieuThuChanged();
    #endregion
		
		public CHI_TIET_HOA_DON()
		{
			this._DICH_VU = default(EntityRef<DICH_VU>);
			this._HOA_DON = default(EntityRef<HOA_DON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTHD", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTHD
		{
			get
			{
				return this._MaCTHD;
			}
			set
			{
				if ((this._MaCTHD != value))
				{
					this.OnMaCTHDChanging(value);
					this.SendPropertyChanging();
					this._MaCTHD = value;
					this.SendPropertyChanged("MaCTHD");
					this.OnMaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HOA_DON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					if (this._DICH_VU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThangNam", DbType="Date NOT NULL")]
		public System.DateTime ThangNam
		{
			get
			{
				return this._ThangNam;
			}
			set
			{
				if ((this._ThangNam != value))
				{
					this.OnThangNamChanging(value);
					this.SendPropertyChanging();
					this._ThangNam = value;
					this.SendPropertyChanged("ThangNam");
					this.OnThangNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoCu", DbType="Float NOT NULL")]
		public double ChiSoCu
		{
			get
			{
				return this._ChiSoCu;
			}
			set
			{
				if ((this._ChiSoCu != value))
				{
					this.OnChiSoCuChanging(value);
					this.SendPropertyChanging();
					this._ChiSoCu = value;
					this.SendPropertyChanged("ChiSoCu");
					this.OnChiSoCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoMoi", DbType="Float NOT NULL")]
		public double ChiSoMoi
		{
			get
			{
				return this._ChiSoMoi;
			}
			set
			{
				if ((this._ChiSoMoi != value))
				{
					this.OnChiSoMoiChanging(value);
					this.SendPropertyChanging();
					this._ChiSoMoi = value;
					this.SendPropertyChanged("ChiSoMoi");
					this.OnChiSoMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTieuThu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiTieuThu
		{
			get
			{
				return this._LoaiTieuThu;
			}
			set
			{
				if ((this._LoaiTieuThu != value))
				{
					this.OnLoaiTieuThuChanging(value);
					this.SendPropertyChanging();
					this._LoaiTieuThu = value;
					this.SendPropertyChanged("LoaiTieuThu");
					this.OnLoaiTieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICH_VU_CHI_TIET_HOA_DON", Storage="_DICH_VU", ThisKey="MaDichVu", OtherKey="MaDichVu", IsForeignKey=true)]
		public DICH_VU DICH_VU
		{
			get
			{
				return this._DICH_VU.Entity;
			}
			set
			{
				DICH_VU previousValue = this._DICH_VU.Entity;
				if (((previousValue != value) 
							|| (this._DICH_VU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICH_VU.Entity = null;
						previousValue.CHI_TIET_HOA_DONs.Remove(this);
					}
					this._DICH_VU.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_HOA_DONs.Add(this);
						this._MaDichVu = value.MaDichVu;
					}
					else
					{
						this._MaDichVu = default(string);
					}
					this.SendPropertyChanged("DICH_VU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CHI_TIET_HOA_DON", Storage="_HOA_DON", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HOA_DON HOA_DON
		{
			get
			{
				return this._HOA_DON.Entity;
			}
			set
			{
				HOA_DON previousValue = this._HOA_DON.Entity;
				if (((previousValue != value) 
							|| (this._HOA_DON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOA_DON.Entity = null;
						previousValue.CHI_TIET_HOA_DONs.Remove(this);
					}
					this._HOA_DON.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_HOA_DONs.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HOA_DON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHU_TRO")]
	public partial class CHU_TRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChuTro;
		
		private string _HoTen;
		
		private string _SDT;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _CCCD;
		
		private string _Email;
		
		private EntitySet<HOP_DONG_THUE> _HOP_DONG_THUEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuTroChanging(string value);
    partial void OnMaChuTroChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public CHU_TRO()
		{
			this._HOP_DONG_THUEs = new EntitySet<HOP_DONG_THUE>(new Action<HOP_DONG_THUE>(this.attach_HOP_DONG_THUEs), new Action<HOP_DONG_THUE>(this.detach_HOP_DONG_THUEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuTro", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChuTro
		{
			get
			{
				return this._MaChuTro;
			}
			set
			{
				if ((this._MaChuTro != value))
				{
					this.OnMaChuTroChanging(value);
					this.SendPropertyChanging();
					this._MaChuTro = value;
					this.SendPropertyChanged("MaChuTro");
					this.OnMaChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHU_TRO_HOP_DONG_THUE", Storage="_HOP_DONG_THUEs", ThisKey="MaChuTro", OtherKey="MaChuTro")]
		public EntitySet<HOP_DONG_THUE> HOP_DONG_THUEs
		{
			get
			{
				return this._HOP_DONG_THUEs;
			}
			set
			{
				this._HOP_DONG_THUEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.CHU_TRO = this;
		}
		
		private void detach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.CHU_TRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICH_VU")]
	public partial class DICH_VU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDichVu;
		
		private string _TenDichVu;
		
		private decimal _DonGia;
		
		private EntitySet<CHI_TIET_HOA_DON> _CHI_TIET_HOA_DONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDichVuChanging(string value);
    partial void OnMaDichVuChanged();
    partial void OnTenDichVuChanging(string value);
    partial void OnTenDichVuChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    #endregion
		
		public DICH_VU()
		{
			this._CHI_TIET_HOA_DONs = new EntitySet<CHI_TIET_HOA_DON>(new Action<CHI_TIET_HOA_DON>(this.attach_CHI_TIET_HOA_DONs), new Action<CHI_TIET_HOA_DON>(this.detach_CHI_TIET_HOA_DONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDichVu", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDichVu
		{
			get
			{
				return this._TenDichVu;
			}
			set
			{
				if ((this._TenDichVu != value))
				{
					this.OnTenDichVuChanging(value);
					this.SendPropertyChanging();
					this._TenDichVu = value;
					this.SendPropertyChanged("TenDichVu");
					this.OnTenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(10,2) NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICH_VU_CHI_TIET_HOA_DON", Storage="_CHI_TIET_HOA_DONs", ThisKey="MaDichVu", OtherKey="MaDichVu")]
		public EntitySet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this._CHI_TIET_HOA_DONs;
			}
			set
			{
				this._CHI_TIET_HOA_DONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.DICH_VU = this;
		}
		
		private void detach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.DICH_VU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOA_DON")]
	public partial class HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaHopDong;
		
		private System.DateTime _NgayTao;
		
		private decimal _TongTien;
		
		private string _PhuongThucTT;
		
		private System.DateTime _HanDong;
		
		private string _TrangThaiHD;
		
		private string _KyThanhToan;
		
		private decimal _PhuThu;
		
		private string _GhiChu;
		
		private EntitySet<CHI_TIET_HOA_DON> _CHI_TIET_HOA_DONs;
		
		private EntityRef<HOP_DONG_THUE> _HOP_DONG_THUE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnTongTienChanging(decimal value);
    partial void OnTongTienChanged();
    partial void OnPhuongThucTTChanging(string value);
    partial void OnPhuongThucTTChanged();
    partial void OnHanDongChanging(System.DateTime value);
    partial void OnHanDongChanged();
    partial void OnTrangThaiHDChanging(string value);
    partial void OnTrangThaiHDChanged();
    partial void OnKyThanhToanChanging(string value);
    partial void OnKyThanhToanChanged();
    partial void OnPhuThuChanging(decimal value);
    partial void OnPhuThuChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HOA_DON()
		{
			this._CHI_TIET_HOA_DONs = new EntitySet<CHI_TIET_HOA_DON>(new Action<CHI_TIET_HOA_DON>(this.attach_CHI_TIET_HOA_DONs), new Action<CHI_TIET_HOA_DON>(this.detach_CHI_TIET_HOA_DONs));
			this._HOP_DONG_THUE = default(EntityRef<HOP_DONG_THUE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HOP_DONG_THUE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(10,2) NOT NULL")]
		public decimal TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucTT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PhuongThucTT
		{
			get
			{
				return this._PhuongThucTT;
			}
			set
			{
				if ((this._PhuongThucTT != value))
				{
					this.OnPhuongThucTTChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucTT = value;
					this.SendPropertyChanged("PhuongThucTT");
					this.OnPhuongThucTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanDong", DbType="Date NOT NULL")]
		public System.DateTime HanDong
		{
			get
			{
				return this._HanDong;
			}
			set
			{
				if ((this._HanDong != value))
				{
					this.OnHanDongChanging(value);
					this.SendPropertyChanging();
					this._HanDong = value;
					this.SendPropertyChanged("HanDong");
					this.OnHanDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHD", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TrangThaiHD
		{
			get
			{
				return this._TrangThaiHD;
			}
			set
			{
				if ((this._TrangThaiHD != value))
				{
					this.OnTrangThaiHDChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiHD = value;
					this.SendPropertyChanged("TrangThaiHD");
					this.OnTrangThaiHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyThanhToan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KyThanhToan
		{
			get
			{
				return this._KyThanhToan;
			}
			set
			{
				if ((this._KyThanhToan != value))
				{
					this.OnKyThanhToanChanging(value);
					this.SendPropertyChanging();
					this._KyThanhToan = value;
					this.SendPropertyChanged("KyThanhToan");
					this.OnKyThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuThu", DbType="Decimal(10,2) NOT NULL")]
		public decimal PhuThu
		{
			get
			{
				return this._PhuThu;
			}
			set
			{
				if ((this._PhuThu != value))
				{
					this.OnPhuThuChanging(value);
					this.SendPropertyChanging();
					this._PhuThu = value;
					this.SendPropertyChanged("PhuThu");
					this.OnPhuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CHI_TIET_HOA_DON", Storage="_CHI_TIET_HOA_DONs", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this._CHI_TIET_HOA_DONs;
			}
			set
			{
				this._CHI_TIET_HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOP_DONG_THUE_HOA_DON", Storage="_HOP_DONG_THUE", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HOP_DONG_THUE HOP_DONG_THUE
		{
			get
			{
				return this._HOP_DONG_THUE.Entity;
			}
			set
			{
				HOP_DONG_THUE previousValue = this._HOP_DONG_THUE.Entity;
				if (((previousValue != value) 
							|| (this._HOP_DONG_THUE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOP_DONG_THUE.Entity = null;
						previousValue.HOA_DONs.Remove(this);
					}
					this._HOP_DONG_THUE.Entity = value;
					if ((value != null))
					{
						value.HOA_DONs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HOP_DONG_THUE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.HOA_DON = this;
		}
		
		private void detach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.HOA_DON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOP_DONG_THUE")]
	public partial class HOP_DONG_THUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private string _MaPhongTro;
		
		private string _MaChuTro;
		
		private string _MaNguoiThue;
		
		private string _TrangThai;
		
		private string _DieuKhoan;
		
		private decimal _TienCoc;
		
		private System.DateTime _NgayDangKy;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private decimal _GiaThue;
		
		private EntitySet<HOA_DON> _HOA_DONs;
		
		private EntityRef<CHU_TRO> _CHU_TRO;
		
		private EntityRef<NGUOI_THUE> _NGUOI_THUE;
		
		private EntityRef<PHONG_TRO> _PHONG_TRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnMaPhongTroChanging(string value);
    partial void OnMaPhongTroChanged();
    partial void OnMaChuTroChanging(string value);
    partial void OnMaChuTroChanged();
    partial void OnMaNguoiThueChanging(string value);
    partial void OnMaNguoiThueChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnDieuKhoanChanging(string value);
    partial void OnDieuKhoanChanged();
    partial void OnTienCocChanging(decimal value);
    partial void OnTienCocChanged();
    partial void OnNgayDangKyChanging(System.DateTime value);
    partial void OnNgayDangKyChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnGiaThueChanging(decimal value);
    partial void OnGiaThueChanged();
    #endregion
		
		public HOP_DONG_THUE()
		{
			this._HOA_DONs = new EntitySet<HOA_DON>(new Action<HOA_DON>(this.attach_HOA_DONs), new Action<HOA_DON>(this.detach_HOA_DONs));
			this._CHU_TRO = default(EntityRef<CHU_TRO>);
			this._NGUOI_THUE = default(EntityRef<NGUOI_THUE>);
			this._PHONG_TRO = default(EntityRef<PHONG_TRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongTro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaPhongTro
		{
			get
			{
				return this._MaPhongTro;
			}
			set
			{
				if ((this._MaPhongTro != value))
				{
					if (this._PHONG_TRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongTroChanging(value);
					this.SendPropertyChanging();
					this._MaPhongTro = value;
					this.SendPropertyChanged("MaPhongTro");
					this.OnMaPhongTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuTro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaChuTro
		{
			get
			{
				return this._MaChuTro;
			}
			set
			{
				if ((this._MaChuTro != value))
				{
					if (this._CHU_TRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuTroChanging(value);
					this.SendPropertyChanging();
					this._MaChuTro = value;
					this.SendPropertyChanged("MaChuTro");
					this.OnMaChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiThue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaNguoiThue
		{
			get
			{
				return this._MaNguoiThue;
			}
			set
			{
				if ((this._MaNguoiThue != value))
				{
					if (this._NGUOI_THUE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiThueChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiThue = value;
					this.SendPropertyChanged("MaNguoiThue");
					this.OnMaNguoiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DieuKhoan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DieuKhoan
		{
			get
			{
				return this._DieuKhoan;
			}
			set
			{
				if ((this._DieuKhoan != value))
				{
					this.OnDieuKhoanChanging(value);
					this.SendPropertyChanging();
					this._DieuKhoan = value;
					this.SendPropertyChanged("DieuKhoan");
					this.OnDieuKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienCoc", DbType="Decimal(10,2) NOT NULL")]
		public decimal TienCoc
		{
			get
			{
				return this._TienCoc;
			}
			set
			{
				if ((this._TienCoc != value))
				{
					this.OnTienCocChanging(value);
					this.SendPropertyChanging();
					this._TienCoc = value;
					this.SendPropertyChanged("TienCoc");
					this.OnTienCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="Date NOT NULL")]
		public System.DateTime NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Decimal(10,2) NOT NULL")]
		public decimal GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOP_DONG_THUE_HOA_DON", Storage="_HOA_DONs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<HOA_DON> HOA_DONs
		{
			get
			{
				return this._HOA_DONs;
			}
			set
			{
				this._HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHU_TRO_HOP_DONG_THUE", Storage="_CHU_TRO", ThisKey="MaChuTro", OtherKey="MaChuTro", IsForeignKey=true)]
		public CHU_TRO CHU_TRO
		{
			get
			{
				return this._CHU_TRO.Entity;
			}
			set
			{
				CHU_TRO previousValue = this._CHU_TRO.Entity;
				if (((previousValue != value) 
							|| (this._CHU_TRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHU_TRO.Entity = null;
						previousValue.HOP_DONG_THUEs.Remove(this);
					}
					this._CHU_TRO.Entity = value;
					if ((value != null))
					{
						value.HOP_DONG_THUEs.Add(this);
						this._MaChuTro = value.MaChuTro;
					}
					else
					{
						this._MaChuTro = default(string);
					}
					this.SendPropertyChanged("CHU_TRO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOI_THUE_HOP_DONG_THUE", Storage="_NGUOI_THUE", ThisKey="MaNguoiThue", OtherKey="MaNguoiThue", IsForeignKey=true)]
		public NGUOI_THUE NGUOI_THUE
		{
			get
			{
				return this._NGUOI_THUE.Entity;
			}
			set
			{
				NGUOI_THUE previousValue = this._NGUOI_THUE.Entity;
				if (((previousValue != value) 
							|| (this._NGUOI_THUE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOI_THUE.Entity = null;
						previousValue.HOP_DONG_THUEs.Remove(this);
					}
					this._NGUOI_THUE.Entity = value;
					if ((value != null))
					{
						value.HOP_DONG_THUEs.Add(this);
						this._MaNguoiThue = value.MaNguoiThue;
					}
					else
					{
						this._MaNguoiThue = default(string);
					}
					this.SendPropertyChanged("NGUOI_THUE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_TRO_HOP_DONG_THUE", Storage="_PHONG_TRO", ThisKey="MaPhongTro", OtherKey="MaPhongTro", IsForeignKey=true)]
		public PHONG_TRO PHONG_TRO
		{
			get
			{
				return this._PHONG_TRO.Entity;
			}
			set
			{
				PHONG_TRO previousValue = this._PHONG_TRO.Entity;
				if (((previousValue != value) 
							|| (this._PHONG_TRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG_TRO.Entity = null;
						previousValue.HOP_DONG_THUEs.Remove(this);
					}
					this._PHONG_TRO.Entity = value;
					if ((value != null))
					{
						value.HOP_DONG_THUEs.Add(this);
						this._MaPhongTro = value.MaPhongTro;
					}
					else
					{
						this._MaPhongTro = default(string);
					}
					this.SendPropertyChanged("PHONG_TRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.HOP_DONG_THUE = this;
		}
		
		private void detach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.HOP_DONG_THUE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOI_THUE")]
	public partial class NGUOI_THUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiThue;
		
		private string _HoTen;
		
		private string _SDT;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _CCCD;
		
		private string _Email;
		
		private EntitySet<HOP_DONG_THUE> _HOP_DONG_THUEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiThueChanging(string value);
    partial void OnMaNguoiThueChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public NGUOI_THUE()
		{
			this._HOP_DONG_THUEs = new EntitySet<HOP_DONG_THUE>(new Action<HOP_DONG_THUE>(this.attach_HOP_DONG_THUEs), new Action<HOP_DONG_THUE>(this.detach_HOP_DONG_THUEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiThue", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiThue
		{
			get
			{
				return this._MaNguoiThue;
			}
			set
			{
				if ((this._MaNguoiThue != value))
				{
					this.OnMaNguoiThueChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiThue = value;
					this.SendPropertyChanged("MaNguoiThue");
					this.OnMaNguoiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOI_THUE_HOP_DONG_THUE", Storage="_HOP_DONG_THUEs", ThisKey="MaNguoiThue", OtherKey="MaNguoiThue")]
		public EntitySet<HOP_DONG_THUE> HOP_DONG_THUEs
		{
			get
			{
				return this._HOP_DONG_THUEs;
			}
			set
			{
				this._HOP_DONG_THUEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.NGUOI_THUE = this;
		}
		
		private void detach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.NGUOI_THUE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG_TRO")]
	public partial class PHONG_TRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhongTro;
		
		private string _TrangThaiPT;
		
		private string _TenPT;
		
		private double _DienTich;
		
		private string _DiaChiPT;
		
		private string _GhiChu;
		
		private EntitySet<HOP_DONG_THUE> _HOP_DONG_THUEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongTroChanging(string value);
    partial void OnMaPhongTroChanged();
    partial void OnTrangThaiPTChanging(string value);
    partial void OnTrangThaiPTChanged();
    partial void OnTenPTChanging(string value);
    partial void OnTenPTChanged();
    partial void OnDienTichChanging(double value);
    partial void OnDienTichChanged();
    partial void OnDiaChiPTChanging(string value);
    partial void OnDiaChiPTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public PHONG_TRO()
		{
			this._HOP_DONG_THUEs = new EntitySet<HOP_DONG_THUE>(new Action<HOP_DONG_THUE>(this.attach_HOP_DONG_THUEs), new Action<HOP_DONG_THUE>(this.detach_HOP_DONG_THUEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongTro", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhongTro
		{
			get
			{
				return this._MaPhongTro;
			}
			set
			{
				if ((this._MaPhongTro != value))
				{
					this.OnMaPhongTroChanging(value);
					this.SendPropertyChanging();
					this._MaPhongTro = value;
					this.SendPropertyChanged("MaPhongTro");
					this.OnMaPhongTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiPT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrangThaiPT
		{
			get
			{
				return this._TrangThaiPT;
			}
			set
			{
				if ((this._TrangThaiPT != value))
				{
					this.OnTrangThaiPTChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiPT = value;
					this.SendPropertyChanged("TrangThaiPT");
					this.OnTrangThaiPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPT
		{
			get
			{
				return this._TenPT;
			}
			set
			{
				if ((this._TenPT != value))
				{
					this.OnTenPTChanging(value);
					this.SendPropertyChanging();
					this._TenPT = value;
					this.SendPropertyChanged("TenPT");
					this.OnTenPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="Float NOT NULL")]
		public double DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiPT", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DiaChiPT
		{
			get
			{
				return this._DiaChiPT;
			}
			set
			{
				if ((this._DiaChiPT != value))
				{
					this.OnDiaChiPTChanging(value);
					this.SendPropertyChanging();
					this._DiaChiPT = value;
					this.SendPropertyChanged("DiaChiPT");
					this.OnDiaChiPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_TRO_HOP_DONG_THUE", Storage="_HOP_DONG_THUEs", ThisKey="MaPhongTro", OtherKey="MaPhongTro")]
		public EntitySet<HOP_DONG_THUE> HOP_DONG_THUEs
		{
			get
			{
				return this._HOP_DONG_THUEs;
			}
			set
			{
				this._HOP_DONG_THUEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.PHONG_TRO = this;
		}
		
		private void detach_HOP_DONG_THUEs(HOP_DONG_THUE entity)
		{
			this.SendPropertyChanging();
			entity.PHONG_TRO = null;
		}
	}
}
#pragma warning restore 1591
